[general]
import = [ "themes/ayu_dark.toml" ]

[terminal]
shell = "fish"

[font]
size = 11.5 # Default: 11.5
normal = { family = "JetBrains Mono", style = "Regular" }

[cursor]
style = { shape = "Beam" }
